In [38]:
import numpy as np
print(np.nan != np.nan)
print(np.nan == np.nan)
print(None != None)
print(None == None)

True
False
False
True

In [39]:
import pandas as pd

In [40]:
# Getting variables of series in array format
series = pd.Series([1, 2, 3])
print(series.values)

[1 2 3]

In [41]:
# To transport from array to list
l = []
l = series.values.tolist()
print(l)

[1, 2, 3]

In [42]:
# Labeling the index pd.Series(data = [series], index = [labels])
series = pd.Series(['a', 'b', 'c'], index = [1, 2, 3])
print(series)
# Or
series.index = [11, 22, 33]
print(series)

1    a
2    b
3    c
dtype: object
11    a
22    b
33    c
dtype: object

In [43]:
# Applying numpy functions to series
import numpy as np
series = pd.Series([1, 2, 3], index = ['a', 'b', 'c'])
summ = np.sum(series)
print(summ)
print(np.log(series))

6
a    0.000000
b    0.693147
c    1.098612
dtype: float64

In [44]:
# Series also can be formed by dictionary
data = {'a': 1, 'b': 2, 'c': 3}
series = pd.Series(data)
print(series)
# Or like
a = [1, 2, 3]
b = ['a', 'b', 'c']
series = pd.Series(dict(zip(a, b)))
print(series)

a    1
b    2
c    3
dtype: int64
1    a
2    b
3    c
dtype: object

In [45]:
# Replacing
# inplace=True → edit the original
# inplace=False → create a new one, leave original safe
df = pd.DataFrame()
df['First'] = [1, 2, np.nan, 4, np.nan]
df.replace({np.nan: 3}, inplace = True)
print(df)

   First
0    1.0
1    2.0
2    3.0
3    4.0
4    3.0

In [46]:
# Value count gives number of duplicating values
df = pd.DataFrame()
df['Orig'] = [1, 2, 2, 3, 4]
print(df.value_counts())

Orig
2       2
1       1
3       1
4       1
Name: count, dtype: int64

In [47]:
# If data is big, .head(n) outputs first n rows, .tail(n) outputs last n rows(5 by default)
df = pd.DataFrame()
df['Orig'] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(df.head())
print('-----------')
print(df.tail())

   Orig
0     1
1     2
2     3
3     4
4     5
-----------
   Orig
5     6
6     7
7     8
8     9
9    10

In [48]:
# Away to select ceratin types of values .select_dtypes(include = ['...'])
df = pd.DataFrame({
    'A': [1, 2, 3],           # int
    'B': [1.1, 2.2, 3.3],     # float
    'C': ['x', 'y', 'z']      # object (string)
})

numeric_df = df.select_dtypes(include = 'int')
print(numeric_df)

   A
0  1
1  2
2  3

In [49]:
# Common way to detect any missing datas(nan's) in dataframe
print(df.isna().sum())

A    0
B    0
C    0
dtype: int64

In [50]:
# Applying lambda function to series

s = pd.Series([1, 2, 3, 4])
print(s.apply(lambda x: x*2))

0    2
1    4
2    6
3    8
dtype: int64

In [51]:
# Columns of the dataframe
df = pd.DataFrame({'first': [1, 2, 3], 'second': [4, 5, 6]})
print(df.columns)

Index(['first', 'second'], dtype='object')

In [52]:
# Renaming columm
df.rename(columns = {'first': 'second', 'second': 'third'}, inplace = True)
print(df)

   second  third
0       1      4
1       2      5
2       3      6

In [53]:
# iloc → integer-location based
df = pd.DataFrame({
    'A': [10, 20, 30],
    'B': [40, 50, 60]
})
# Select first row
print(df.iloc[0])

A    10
B    40
Name: 0, dtype: int64

In [54]:
# loc → label-based
df.index = ['x', 'y', 'z']
print(df.loc['x'])

A    10
B    40
Name: x, dtype: int64

In [55]:
# Finding position of the column
df = pd.DataFrame({
    'A': [10, 20, 30],
    'B': [40, 50, 60],
    'C': [70, 80, 90]
})

# Find position of column 'B'
pos = df.columns.get_loc('B')
print(pos)

1

In [56]:
# Dropping a row
df = pd.DataFrame({
    'A': [10, 20, 30],
    'B': [40, 50, 60]
}, index=['x','y','z'])

new_df = df.drop('y', axis = 0)
print(new_df)

# Dropping column
new_df = df.drop('A', axis = 1)
print(new_df)

    A   B
x  10  40
z  30  60
    B
x  40
y  50
z  60

In [57]:
# del is only for deleting columns
df = pd.DataFrame({
    'A': [1,2,3],
    'B': [4,5,6],
    'C': [7,8,9]
})

del df['B']
print(df)

   A  C
0  1  7
1  2  8
2  3  9

In [58]:
# Setting new index
df = pd.DataFrame({
    'ID': [101, 102, 103],
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Score': [85, 90, 95]
})

new_df = df.set_index('ID')
print(new_df)

        Name  Score
ID
101    Alice     85
102      Bob     90
103  Charlie     95

In [59]:
# And resetting
df.reset_index()

   index   ID     Name  Score
0      0  101    Alice     85
1      1  102      Bob     90
2      2  103  Charlie     95

In [60]:
# Sorting by certain columns .sort_values(by = 'column name', ascending = True/False(descending))
df = pd.DataFrame({
    'ID': [103, 102, 101],
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Score': [85, 90, 95]
})
print(df.sort_values(by = 'ID', ascending = True))

    ID     Name  Score
2  101  Charlie     95
1  102      Bob     90
0  103    Alice     85

In [61]:
# Reindex to assign new values to indexes .reindex([index 1, index 2, .....], fill_value = value, columns = [column name 1, ...])
df = pd.DataFrame({
    'ID': [103, 102, 101],
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Score': [85, 90, 95]
})
df = df.reindex([0, 1, 2, 3], fill_value = 'unknown', columns = ['ID', 'Name'])
print(df)

        ID     Name
0      103    Alice
1      102      Bob
2      101  Charlie
3  unknown  unknown

In [62]:
# Dropping duplicates from data
# df.drop_duplicates(subset=None, keep='first', inplace=False)
#subset → column(s) to check for duplicates (default: all columns)
#keep → which duplicate to keep:
#'first' → keep first occurrence
#'last' → keep last occurrence
#False → remove all duplicates
#inplace → modify the original DataFrame (default: False)
data = {
    'ID': [101, 102, 102, 103, 103, 103],
    'Name': ['Alice', 'Bob', 'Bob', 'Charlie', 'Charlie', 'Charlie'],
    'Score': [85, 90, 90, 95, 95, 95]
}

df = pd.DataFrame(data)

print("Before:\n", df)

df_unique = df.drop_duplicates()
print("\nAfter drop_duplicates():\n", df_unique)

Before:
     ID     Name  Score
0  101    Alice     85
1  102      Bob     90
2  102      Bob     90
3  103  Charlie     95
4  103  Charlie     95
5  103  Charlie     95

After drop_duplicates():
     ID     Name  Score
0  101    Alice     85
1  102      Bob     90
3  103  Charlie     95

In [63]:
# Adding new rows
df1 = pd.DataFrame({'ID':[101,102], 'Name':['Alice','Bob']})
df2 = pd.DataFrame({'ID':[103], 'Name':['Charlie']})

df_new = pd.concat([df1, df2], ignore_index=True)
print(df_new)

    ID     Name
0  101    Alice
1  102      Bob
2  103  Charlie

In [64]:
# Data importing
df = pd.read_csv('ncr_ride_bookings.csv')
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

In [65]:
# Description of the dataframe
df.describe()

,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Cancelled Rides by Driver,Incomplete Rides,Booking Value,Ride Distance,Driver Ratings,Customer Rating
count,139500.000000,102000.000000,10500.0,27000.0,9000.0,102000.000000,102000.000000,93000.000000,93000.000000
mean,8.456352,29.149636,1.0,1.0,1.0,508.295912,24.637012,4.230992,4.404584
std,3.773564,8.902577,0.0,0.0,0.0,395.805774,14.002138,0.436871,0.437819
min,2.000000,10.000000,1.0,1.0,1.0,50.000000,1.000000,3.000000,3.000000
25%,5.300000,21.600000,1.0,1.0,1.0,234.000000,12.460000,4.100000,4.200000
50%,8.300000,28.800000,1.0,1.0,1.0,414.000000,23.720000,4.300000,4.500000
75%,11.300000,36.800000,1.0,1.0,1.0,689.000000,36.820000,4.600000,4.800000
max,20.000000,45.000000,1.0,1.0,1.0,4277.000000,50.000000,5.000000,5.000000

In [66]:
# Sep is modifying separator in case in csv data is separated by another indexes
df_sep = pd.read_csv('ncr_ride_bookings.csv', sep = ',')
df_sep.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

In [67]:
# To skip rows skiprows = number of rows from head, skiprows = [specific rows], skiprows = lambda x: condition
df_skiprows = pd.read_csv('ncr_ride_bookings.csv', skiprows = 3)
df_skiprows.head()

,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,null.1,null.2,null.3,null.4,null.5,627,13.58,4.9,4.9.1,Debit Card
0,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
1,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI
2,2024-02-06,09:44:56,"""CNR4096693""",Completed,"""CID4670564""",Auto,AIIMS,Narsinghpur,5.1,18.1,...,NaN,NaN,NaN,NaN,NaN,316.0,4.85,4.1,4.6,UPI
3,2024-06-17,15:45:58,"""CNR2002539""",Completed,"""CID6800553""",Go Mini,Vaishali,Punjabi Bagh,7.1,20.4,...,NaN,NaN,NaN,NaN,NaN,640.0,41.24,4.0,4.1,UPI
4,2024-03-19,17:37:37,"""CNR6568000""",Completed,"""CID8610436""",Auto,Mayur Vihar,Cyber Hub,12.1,16.5,...,NaN,NaN,NaN,NaN,NaN,136.0,6.56,4.4,4.2,UPI

In [68]:
# Nrows works like .head()
df_nrows = pd.read_csv('ncr_ride_bookings.csv', nrows = 3)
df_nrows.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card

In [69]:
# Changing index of the data
df_index = pd.read_csv('ncr_ride_bookings.csv', index_col = 'Date')
df_index.head()

,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
Date,,,,,,,,,,,,,,,,,,,,
2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,NaN,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,NaN,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,NaN,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,NaN,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

In [70]:
# Dividing by chunks
chunks = pd.read_csv('ncr_ride_bookings.csv', nrows = 4, chunksize = 2)
for chunk in chunks:
    print(chunk)
    print('------------------------------------------------------------------')

         Date      Time    Booking ID   Booking Status   Customer ID  \
0  2024-03-23  12:29:38  "CNR5884300"  No Driver Found  "CID1982111"
1  2024-11-29  18:01:39  "CNR1326809"       Incomplete  "CID4604802"

  Vehicle Type Pickup Location      Drop Location  Avg VTAT  Avg CTAT  ...  \
0        eBike     Palam Vihar            Jhilmil       NaN       NaN  ...
1     Go Sedan   Shastri Nagar  Gurgaon Sector 56       4.9      14.0  ...

   Reason for cancelling by Customer  Cancelled Rides by Driver  \
0                                NaN                        NaN
1                                NaN                        NaN

   Driver Cancellation Reason  Incomplete Rides  Incomplete Rides Reason  \
0                         NaN               NaN                      NaN
1                         NaN               1.0        Vehicle Breakdown

  Booking Value  Ride Distance  Driver Ratings  Customer Rating  \
0           NaN            NaN             NaN              NaN
1         237.0           5.73             NaN              NaN

   Payment Method
0             NaN
1             UPI

[2 rows x 21 columns]
------------------------------------------------------------------
         Date      Time    Booking ID Booking Status   Customer ID  \
2  2024-08-23  08:56:10  "CNR8494506"      Completed  "CID9202816"
3  2024-10-21  17:17:25  "CNR8906825"      Completed  "CID2610914"

    Vehicle Type      Pickup Location  Drop Location  Avg VTAT  Avg CTAT  ...  \
2           Auto              Khandsa  Malviya Nagar      13.4      25.8  ...
3  Premier Sedan  Central Secretariat       Inderlok      13.1      28.5  ...

   Reason for cancelling by Customer  Cancelled Rides by Driver  \
2                                NaN                        NaN
3                                NaN                        NaN

   Driver Cancellation Reason  Incomplete Rides  Incomplete Rides Reason  \
2                         NaN               NaN                      NaN
3                         NaN               NaN                      NaN

   Booking Value  Ride Distance  Driver Ratings  Customer Rating  \
2            627          13.58             4.9              4.9
3            416          34.02             4.6              5.0

   Payment Method
2      Debit Card
3             UPI

[2 rows x 21 columns]
------------------------------------------------------------------

In [71]:
# To replace missing values with NaN
df = pd.read_csv('ncr_ride_bookings.csv', nrows = 5, na_values = ['Incomplete'])
print(df)

         Date      Time    Booking ID   Booking Status   Customer ID  \
0  2024-03-23  12:29:38  "CNR5884300"  No Driver Found  "CID1982111"
1  2024-11-29  18:01:39  "CNR1326809"              NaN  "CID4604802"
2  2024-08-23  08:56:10  "CNR8494506"        Completed  "CID9202816"
3  2024-10-21  17:17:25  "CNR8906825"        Completed  "CID2610914"
4  2024-09-16  22:08:00  "CNR1950162"        Completed  "CID9933542"

    Vehicle Type      Pickup Location      Drop Location  Avg VTAT  Avg CTAT  \
0          eBike          Palam Vihar            Jhilmil       NaN       NaN
1       Go Sedan        Shastri Nagar  Gurgaon Sector 56       4.9      14.0
2           Auto              Khandsa      Malviya Nagar      13.4      25.8
3  Premier Sedan  Central Secretariat           Inderlok      13.1      28.5
4           Bike     Ghitorni Village        Khan Market       5.3      19.6

   ...  Reason for cancelling by Customer  Cancelled Rides by Driver  \
0  ...                                NaN                        NaN
1  ...                                NaN                        NaN
2  ...                                NaN                        NaN
3  ...                                NaN                        NaN
4  ...                                NaN                        NaN

   Driver Cancellation Reason  Incomplete Rides  Incomplete Rides Reason  \
0                         NaN               NaN                      NaN
1                         NaN               1.0        Vehicle Breakdown
2                         NaN               NaN                      NaN
3                         NaN               NaN                      NaN
4                         NaN               NaN                      NaN

  Booking Value  Ride Distance  Driver Ratings  Customer Rating  \
0           NaN            NaN             NaN              NaN
1         237.0           5.73             NaN              NaN
2         627.0          13.58             4.9              4.9
3         416.0          34.02             4.6              5.0
4         737.0          48.21             4.1              4.3

   Payment Method
0             NaN
1             UPI
2      Debit Card
3             UPI
4             UPI

[5 rows x 21 columns]

In [72]:
# To get rid of null values
df[df.notnull()].head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",NaN,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

In [73]:
# Also can get rid of Nan's
df_no_nans = df.dropna()
df_no_nans.head()

Empty DataFrame
Columns: [Date, Time, Booking ID, Booking Status, Customer ID, Vehicle Type, Pickup Location, Drop Location, Avg VTAT, Avg CTAT, Cancelled Rides by Customer, Reason for cancelling by Customer, Cancelled Rides by Driver, Driver Cancellation Reason, Incomplete Rides, Incomplete Rides Reason, Booking Value, Ride Distance, Driver Ratings, Customer Rating, Payment Method]
Index: []

[0 rows x 21 columns]

In [75]:
# Reading excel file
excel = pd.read_excel('covid.xlsx')

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [38]:
# If many sheets(tables) is given, we can specify which one to load
excel = pd.read_excel('covid.xlsx', sheet_name = 0)
excel.head()

,State/UTs,Zone,Total Cases,Active,Discharged,Deaths,Active Ratio,Discharge Ratio,Discharge Avg,Death Ratio,Death Avg,Population
0,Andaman and Nicobar,South,7670,7,7534,129,0.09,98.23,Below Average,1.68,Above Average,399001
1,Andhra Pradesh,South,2069770,3128,2052230,14412,0.15,99.15,Above Average,0.70,Below Average,91702478
2,Arunachal Pradesh,East,55216,42,54894,280,0.08,99.42,Above Average,0.51,Below Average,1711947
3,Assam,East,613784,3272,604465,6047,0.53,98.48,Above Average,0.99,Below Average,35998752
4,Bihar,East,726153,29,716462,9662,0.00,98.67,Above Average,1.33,Above Average,128500364

In [39]:
# We can change headers to indexes
excel = pd.read_excel('covid.xlsx', sheet_name = 0, header = None)
excel.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,State/UTs,Zone,Total Cases,Active,Discharged,Deaths,Active Ratio,Discharge Ratio,Discharge Avg,Death Ratio,Death Avg,Population
1,Andaman and Nicobar,South,7670,7,7534,129,0.09,98.23,Below Average,1.68,Above Average,399001
2,Andhra Pradesh,South,2069770,3128,2052230,14412,0.15,99.15,Above Average,0.7,Below Average,91702478
3,Arunachal Pradesh,East,55216,42,54894,280,0.08,99.42,Above Average,0.51,Below Average,1711947
4,Assam,East,613784,3272,604465,6047,0.53,98.48,Above Average,0.99,Below Average,35998752

In [40]:
# Getting info of the dataframe
excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       37 non-null     object
 1   1       37 non-null     object
 2   2       37 non-null     object
 3   3       37 non-null     object
 4   4       37 non-null     object
 5   5       37 non-null     object
 6   6       37 non-null     object
 7   7       37 non-null     object
 8   8       37 non-null     object
 9   9       37 non-null     object
 10  10      37 non-null     object
 11  11      37 non-null     object
dtypes: object(12)
memory usage: 3.6+ KB

In [41]:
# Time handling
from datetime import datetime

In [42]:
# Time now
time_now = datetime.now()
print(time_now)

2025-08-28 14:21:52.540623

In [43]:
# Specifying
print(time_now.year)
print(time_now.month)
print(time_now.day)
print(time_now.hour)
print(time_now.minute)
print(time_now.second)
print(time_now.microsecond)

2025
8
28
14
21
52
540623

In [44]:
# Also can find day of the week
print(time_now.weekday())

3

In [45]:
# Just hour, minute, seconds, microseconds
print(time_now.time())

14:21:52.540623

In [46]:
# Creating time variables
from datetime import date, time
noon = time(12, 00, 00)
print(noon)
hit = date(1945, 5, 9)
print(hit)

12:00:00
1945-05-09

In [47]:
# Time deltas
my_age = time_now - datetime(2005, 9, 6)
print(type(my_age))
age = my_age.days / 365.25
print(age)

<class 'datetime.timedelta'>
19.975359342915812

In [63]:
# Merging on columns using merge(dataframe, dataframe, dataframe, ..., on = "column name", how = "inner/outer/left/right")
df1 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"]
})

df2 = pd.DataFrame({
    "ID": [1, 2, 4],
    "Score": [85, 90, 95]
})

merged = pd.merge(df1, df2, on="ID", how="inner")
print(merged)

   ID   Name  Score
0   1  Alice     85
1   2    Bob     90

In [70]:
# Joining on indexes using dataframe.join(dataframe, how = "inner/outer/left/right/cross")
df1 = pd.DataFrame({"Name": ["Alice", "Bob", "Charlie"]}, index=[1, 2, 3])
df2 = pd.DataFrame({"Score": [85, 90, 95]}, index=[1, 2, 4])

joined = df1.join(df2, how="inner")
print(joined)

    Name  Score
1  Alice     85
2    Bob     90

In [66]:
# Joining can be done on columns
df1 = pd.DataFrame({"ID": [1, 2, 3], "Name": ["Alice", "Bob", "Charlie"]})
df2 = pd.DataFrame({"ID": [1, 2, 4], "Score": [85, 90, 95]})

joined = df1.join(df2.set_index("ID"), on="ID")
print(joined)

   ID     Name  Score
0   1    Alice   85.0
1   2      Bob   90.0
2   3  Charlie    NaN